---
- hosts: "{{ target }}"

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/ec2.pem

  roles:
    - roles/prepare_host
    - roles/install_k8s
    - roles/add_worker
    - roles/create_sc
